### ISSUE TITLE
Guest 机器启动错误

### ISSUE THREAD

**Issue by sunhaotian0122** [IPADS-DuVisor/kvm-tutorial#1]
构建用于 KVM 的 Qemu 时，只指定 ARCH 和 CROSS_COMPILE 编译出来的 qemu-system-riscv64 还是实际物理机架构的 qemu，在启动第一层虚拟化 RV 架构的 Host 机器后不能在里面运行。交叉编译 RV 架构的 qemu 好像需要指定--cross-prefix，不过我用源码构建的 RV 交叉编译器会提示：ERROR: pkg-config binary 'riscv64-unknown-linux-gnu-pkg-config' not found。
想问下构建 KVM 的 Qemu 时 qemu 是用的哪个版本？只用上诉命令就构建出了 RV 架构的 Qemu 吗？

**Comment by GToad** [comment]
Haotian，你好。

这里的确应当使用--cross-prefix，我们建议在编译guest QEMU这步时按照如下步骤：
先安装riscv交叉编译器

```
sudo apt install gcc-riscv64-linux-gnu pkg-config-riscv64-linux-gnu -y
```

然后在该QEMU目录下执行：
```
./configure --target-list="riscv32-softmmu riscv64-softmmu" --cross-prefix=riscv64-linux-gnu-
```

这时候你反应的”XXXpkg-config' not found“问题应该就解决了。

但是接下来还会有新的报错，在我的ubuntu 20.04上会报注入如glib-2.0 not found或pixman-1 not found
你可能会奇怪这些库你应该已经安装了，这是因为它这时其实需要你安装这些库的riscv64版本，你可以参考这个链接来安装各种架构的库：https://wiki.debian.org/Multiarch/HOWTO

在完成这些以后，configure这步命令应该就能顺利执行完成，接下来make就可以了。我们会尽快更新这个README以使其他人避开这个问题。

非常感谢你的反馈！

**Comment by sunhaotian0122** [comment]
我也很高兴能为这个搭建RISC-V虚拟化环境的指南做贡献。

我按照你说的在 ubuntu 20.04 的 docker 镜像里安装了那些库之后编译成功了，得到了 RISC-V 架构的 qemu。不过你的改动是不是应该放在“构建用于KVM的QEMU”这个标题下，毕竟这是为第二层虚拟化准备的qemu。

另外，即使编译出了 RISC-V 架构的 qemu，如果只是简单的把它放进 HOST rootfs 中，任然不能运行，因为这个用 busybox 编译出的简易的 HOST rootfs 没有 RISC-V 的编译环境，即缺少 lib 库等。

我目前正在想办法解决这个问题，准备把 ubuntu 中下载的 RISC-V 的库放进去制作 rootfs，不过还没有找到下载的全部 RISC-V 架构的库文件。

如果你有更好的办法，请告诉我，感谢！

**Comment by 130B848** [comment]
> 如果只是简单的把它放进 HOST rootfs 中，任然不能运行，因为这个用 busybox 编译出的简易的 HOST rootfs 没有 RISC-V 的编译环境，即缺少 lib 库等。

请在configure时添加`--static`选项，以下是我自用的编译指令以供参考：

```bash
./configure --target-list=riscv64-softmmu --enable-kvm --static \
--cross-prefix=riscv64-linux-gnu- --disable-libiscsi --disable-glusterfs \
--disable-libusb --disable-usb-redir --audio-drv-list= --disable-opengl \
 --disable-linux-io-uring

make ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- -j$(nproc)
```

谢谢。

**Comment by sunhaotian0122** [comment]
实际上我已经通过复制 RISC-V 架构的库解决了这个问题，不过编译静态文件更简单。

但是现在不论是通过复制库还是通过编译静态 qemu 都会在启动第二层虚拟化时遇到错误，这个错误我完全没有头绪，网上也没有找到相关的介绍，以下是错误信息。qemu-system-riscv64-static 是根据你提供的命令编译出的静态 qemu，qemu-system-riscv64 是我通过复制 RISC-V 架构的库运行的qemu。
![image](https://github.com/IPADS-DuVisor/kvm-tutorial/assets/19524078/5099be05-1412-4033-b1f1-8d359c871cce)

看起来似乎是不支持 H 扩展？但是在网上没有找到类似的错误信息，你是否遇到过这种错误？顺便一提，我的 qemu 版本是v8.0.2，按理是支持 RV 的 H 扩展的。

**Comment by 130B848** [comment]
你好，我们使用的是QEMU v7.0.0，没有遇到过这种问题。

不知道你在第一层和第二层用到的QEMU版本是否一致，如果不一致则可能是`priv_spec`不匹配，可以尝试通过调整QEMU启动参数`-cpu rv64,priv_spec=v1.11.0`强制对齐`priv_spec`版本。

**Comment by sunhaotian0122** [comment]
十分感谢你的指导，我用 qemu v7.0.0 版本成功进行了两层虚拟化，目前还不清楚为啥高版本不行，之后会尝试你说的对齐priv_spec 版本。
